version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploy application to sit
          command: npm run deploy:sit
      - run:
          name: Recreate database
          command: npm run seed:sit
      - run:
          name: Run integration tests
          command: TEST_STAGE=sit npm run test:integration
      - run:
          name: Run acceptance tests
          command: npm run test:acceptance
      - run:
          name: Deploy application
          command: npm run deploy:prod